[package]
name = "ghost-student"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
serde = "1.0.228"
serde_json = "1.0.149"
thirtyfour = "0.36.1"
tokio = {version = "1.49.0", features = ["full"]}